import badachro from "./images/badachro.webp";
import sali from "./images/sali.webp";
import gildeskal from "./images/gildeskal.webp";
import murter from "./images/murter.webp";
import vis from "./images/vis.webp";
import opcinaLastovo from "./images/opcina-lastovo.webp";
import uusikaupunki from "./images/uusikaupunki.webp";
import gildeskal2 from "./images/gildeskal2.webp";
import skalen from "./images/skalen.webp";
import ytteran from "./images/ytteran.webp";
import nordland from "./images/nordland.webp";
import murter2 from "./images/murter2.webp";

export default [
  {
    id: 1,
    img: badachro,
    location: "Badachro, UK",
    rating: 4.71,
    distance: 2.761,
    month: "Nov",
    startDay: 17,
    endDay: 22,
    price: 1.015,
  },
  {
    id: 2,
    img: sali,
    location: "Sali, Croatia",
    rating: "NEW",
    distance: 871,
    month: "Oct",
    startDay: 1,
    endDay: 7,
    price: 612,
  },
  {
    id: 3,
    img: gildeskal,
    location: "Gildeskål, Norway",
    rating: 4.83,
    distance: 2.631,
    month: "Sep",
    startDay: 20,
    endDay: 25,
    price: "1.220",
  },
  {
    id: 4,
    img: murter,
    location: "Murter, Croatia",
    rating: "5.0",
    distance: 841,
    month: "Oct",
    startDay: 29,
    endDay: "Nov 5",
    price: 676,
  },
  {
    id: 5,
    img: vis,
    location: "Vis, Croatia",
    rating: "NEW",
    distance: 808,
    month: "Aug",
    startDay: 26,
    endDay: 31,
    price: 6.913,
  },
  {
    id: 6,
    img: opcinaLastovo,
    location: "Općina Lastovo, Croatia",
    rating: "NEW",
    distance: 796,
    month: "Sep",
    startDay: 1,
    endDay: 6,
    price: 629,
  },
  {
    id: 7,
    img: uusikaupunki,
    location: "Uusikaupunki, Finland",
    rating: 4.92,
    distance: 1.848,
    month: "Sep",
    startDay: 4,
    endDay: 11,
    price: 956,
  },
  {
    id: 8,
    img: gildeskal2,
    location: "Gildeskål, Norway",
    rating: "5.0",
    distance: 2.631,
    month: "Sep",
    startDay: 6,
    endDay: 13,
    price: 879,
  },
  {
    id: 9,
    img: skalen,
    location: "Skalen, Sweden",
    rating: 4.59,
    distance: 1.879,
    month: "Oct",
    startDay: 1,
    endDay: 6,
    price: 1.106,
  },
  {
    id: 10,
    img: ytteran,
    location: "Ytterån, Sweden",
    rating: 4.83,
    distance: 2.232,
    month: "Jan",
    startDay: 9,
    endDay: 16,
    price: 1.393,
  },
  {
    id: 11,
    img: nordland,
    location: "Nordland, Norway",
    rating: "5.0",
    distance: 2.727,
    month: "May",
    startDay: 6,
    endDay: 11,
    price: 1.555,
  },
  {
    id: 12,
    img: murter2,
    location: "Murter, Croatia",
    rating: "NEW",
    distance: 855,
    month: "Sep",
    startDay: 11,
    endDay: 18,
    price: 1.731,
  },
];
